import { Game } from "@/lib/features/gamesSlice"

export const gamesArray: Game[] = [
    {
    id: "1",
    name: "Starburst",
    provider: "NetEnt",
    image: "/placeholderImg.png",
    category: "slots",
  },
  {
    id: "2",
    name: "Gonzo’s Quest",
    provider: "NetEnt",
    image: "/placeholderImg.png",
    category: "slots",
  },
  {
    id: "3",
    name: "Sweet Bonanza",
    provider: "Pragmatic Play",
    image: "/placeholderImg.png",
    category: "slots",
  },
  {
    id: "4",
    name: "Book of Dead",
    provider: "Play’n GO",
    image: "/placeholderImg.png",
    category: "slots",
  },
  {
    id: "5",
    name: "Mega Moolah",
    provider: "Microgaming",
    image: "/placeholderImg.png",
    category: "slots",
  },
  {
    id: "6",
    name: "Lightning Roulette",
    provider: "Evolution",
    image: "/placeholderImg.png",
    category: "live",
  },
  {
    id: "7",
    name: "Crazy Time",
    provider: "Evolution",
    image: "/placeholderImg.png",
    category: "live",
  },
  {
    id: "8",
    name: "Monopoly Live",
    provider: "Evolution",
    image: "/placeholderImg.png",
    category: "live",
  },
  {
    id: "9",
    name: "Blackjack Classic",
    provider: "NetEnt",
    image: "/placeholderImg.png",
    category: "table",
  },
  {
    id: "10",
    name: "European Roulette",
    provider: "Playtech",
    image: "/placeholderImg.png",
    category: "table",
  },
  {
    id: "11",
    name: "Baccarat Pro",
    provider: "Evolution",
    image: "/placeholderImg.png",
    category: "table",
  },
  {
    id: "12",
    name: "Texas Hold’em Poker",
    provider: "Playtech",
    image: "/placeholderImg.png",
    category: "table",
  },
  {
    id: "13",
    name: "Reactoonz",
    provider: "Play’n GO",
    image: "/placeholderImg.png",
    category: "slots",
  },
  {
    id: "14",
    name: "Dead or Alive 2",
    provider: "NetEnt",
    image: "/placeholderImg.png",
    category: "slots",
  },
  {
    id: "15",
    name: "Jammin’ Jars",
    provider: "Push Gaming",
    image: "/placeholderImg.png",
    category: "slots",
  },
  {
    id: "16",
    name: "Immersive Roulette",
    provider: "Evolution",
    image: "/placeholderImg.png",
    category: "live",
  },
  {
    id: "17",
    name: "Ultimate Texas Hold’em",
    provider: "Evolution",
    image: "/placeholderImg.png",
    category: "live",
  },
  {
    id: "18",
    name: "Caribbean Stud Poker",
    provider: "Microgaming",
    image: "/placeholderImg.png",
    category: "table",
  },
  {
    id: "19",
    name: "Fruit Party",
    provider: "Pragmatic Play",
    image: "/placeholderImg.png",
    category: "slots",
  },
  {
    id: "20",
    name: "Big Bass Bonanza",
    provider: "Pragmatic Play",
    image: "/placeholderImg.png",
    category: "slots",
  },
]